{
 "title": "pomalu, ale jistĕ ...",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Detectors Train Results",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "train_seller_auto_encoder_current_value"
    },
    {
     "expr": "train_buyer_auto_encoder_current_value"
    }
   ]
  },
  {
   "title": "Decision Maker Train Results",
   "type": "graph",
   "gridPos": { "h": 32, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "train_trader_decision_maker_current_value"
    },
    {
     "expr": "train_trader_decision_maker_best_value"
    }
   ]
  },
  {
   "title": "Classifier Train Results",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "train_trader_classifier_current_value"
    }
   ]
  }
 ]
}