version: "3.3"

services:

    pomalu.ale.jiste.prometheus:
        container_name: pomalu.ale.jiste.prometheus
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - pomalu.ale.jiste

    pomalu.ale.jiste.grafana:
        container_name: pomalu.ale.jiste.grafana
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        user: "472"
        volumes:
            - "./grafana/dashboards:/var/lib/grafana/dashboards"
            - "./grafana/provisioning:/etc/grafana/provisioning"
        networks:
            - pomalu.ale.jiste

networks:
    pomalu.ale.jiste:
