version: "3.3"

services:

    pomalu.ale.jiste.prometheus:
        container_name: pomalu.ale.jiste.prometheus
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - pomalu.ale.jiste

    pomalu.ale.jiste.grafana:
        container_name: pomalu.ale.jiste.grafana
        image: grafana/grafana:latest
        ports:
            - "3010:3000"
        user: "472"
        volumes:
            - grafana_data:/var/lib/grafana
        networks:
            - pomalu.ale.jiste

volumes:
    grafana_data: {}

networks:
    pomalu.ale.jiste:
