version: "3.3"

services:

    pomalu.ale.jiste.prometheus:
        container_name: pomalu.ale.jiste.prometheus
        image: prom/prometheus:latest
        restart: always
        user: "1001:1001"
        ports:
            - "9090:9090"
        volumes:
            - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
            - "./prometheus/data:/prometheus"
        networks:
            - pomalu.ale.jiste
        logging:
            options:
                max-size: "1M"
                max-file: "5"

    pomalu.ale.jiste.grafana:
        container_name: pomalu.ale.jiste.grafana
        image: grafana/grafana:latest
        restart: always
        ports:
            - "3000:3000"
        user: "472"
        volumes:
            - "./grafana/dashboards:/var/lib/grafana/dashboards"
            - "./grafana/provisioning:/etc/grafana/provisioning"
            - "./grafana/grafana.ini:/etc/grafana/grafana.ini:ro"
        networks:
            - pomalu.ale.jiste
        logging:
            options:
                max-size: "1M"
                max-file: "5"

    pomalu.ale.jiste.metrics:
        container_name: pomalu.ale.jiste.metrics
        build:
            dockerfile: Dockerfile
            context: ./metrics
        restart: always
        user: "1001:1001"
        ports:
            - "5001:5001"
        volumes:
            - "./metrics/app:/app"
            - "./metrics/data:/data"
        environment:
            - TIINGO_API_KEY=$TIINGO_API_KEY
        networks:
            - pomalu.ale.jiste
        logging:
            options:
                max-size: "1M"
                max-file: "5"

networks:
    pomalu.ale.jiste:
