{
 "title": "pomalu, ale jistĕ ...",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Buyer train result",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "train_buyer_auto_encoder_current_value",
     "legendFormat": "buyer current loss"
    },
    {
     "expr": "train_buyer_auto_encoder_best_value",
     "legendFormat": "buyer best loss"
    }
   ]
  },
  {
   "title": "Positive profit rates",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 0 },
   "targets": [
    { "expr": "train_trader_current_value" }
   ]
  },
  {
   "title": "Average profit rate",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "train_trader_current_value" }
   ]
  },
  {
   "title": "Seller train result",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "train_seller_auto_encoder_current_value",
     "legendFormat": "seller current loss"
    },
    {
     "expr": "train_seller_auto_encoder_best_value",
     "legendFormat": "seller best loss"
    }
   ]
  },
  {
   "title": "Negative profit rates",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 9, "x": 11, "y": 7 },
   "targets": [
    { "expr": "train_trader_current_value" }
   ]
  },
  {
   "title": "Classifier train result",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "train_classifier_current_value", "legendFormat": "classifier current loss" },
    { "expr": "train_classifier_best_value", "legendFormat": "classifier best loss" }
   ]
  },
  {
   "title": "Trader profit rates",
   "type": "graph",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "train_trader_current_value", "legendFormat": "current profit rate" }
   ]
  },
  {
   "title": "Decision maker mean value",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "train_decision_maker_current_value",
     "legendFormat": "current mean value"
    },
    {
     "expr": "train_decision_maker_best_value",
     "legendFormat": "best mean value"
    }
   ]
  }
 ]
}