{
 "title": "Trades",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "AMD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_price_AMD", "legendFormat": "Last Price" }
   ]
  },
  {
   "title": "AMD",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "trade_price_AMD", "legendFormat": "Trade" },
    { "expr": "bid_price_AMD", "legendFormat": "Bid" },
    { "expr": "ask_price_AMD", "legendFormat": "Ask" }
   ]
  },
  {
   "title": "Micron Technology",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_price_MU", "legendFormat": "Last Price" }
   ]
  },
  {
   "title": "Micron Technology",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "trade_price_MU", "legendFormat": "Trade" },
    { "expr": "bid_price_MU", "legendFormat": "Bid" },
    { "expr": "ask_price_MU", "legendFormat": "Ask" }
   ]
  },
  {
   "title": "Viking Therapeutics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_price_VKTX", "legendFormat": "Last Price" }
   ]
  },
  {
   "title": "Viking Therapeutics",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "trade_price_VKTX", "legendFormat": "Trade" },
    { "expr": "bid_price_VKTX", "legendFormat": "Bid" },
    { "expr": "ask_price_VKTX", "legendFormat": "Ask" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_volume_AMD", "legendFormat": "Volume" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_volume_MU", "legendFormat": "Volume" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_volume_VKTX", "legendFormat": "Volume" }
   ]
  },
  {
   "title": "Nvidia",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_price_NVDA", "legendFormat": "Last Price" }
   ]
  },
  {
   "title": "Nvidia",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "trade_price_NVDA", "legendFormat": "Trade" },
    { "expr": "bid_price_NVDA", "legendFormat": "Bid" },
    { "expr": "ask_price_NVDA", "legendFormat": "Ask" }
   ]
  },
  {
   "title": "Seagate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_price_STX", "legendFormat": "Last Price" }
   ]
  },
  {
   "title": "Seagate",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 2, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "trade_price_STX", "legendFormat": "Trade" },
    { "expr": "bid_price_STX", "legendFormat": "Bid" },
    { "expr": "ask_price_STX", "legendFormat": "Ask" }
   ]
  },
  {
   "title": "PDS Biotechnology",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_price_PDSB", "legendFormat": "Last Price" }
   ]
  },
  {
   "title": "PDS Biotechnology",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "trade_price_PDSB", "legendFormat": "Trade" },
    { "expr": "bid_price_PDSB", "legendFormat": "Bid" },
    { "expr": "ask_price_PDSB", "legendFormat": "Ask" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_volume_NVDA", "legendFormat": "Volume" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_volume_STX", "legendFormat": "Volume" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trade_volume_PDSB", "legendFormat": "Volume" }
   ]
  }
 ]
}